server:
  port: 8080

spring:
    application:
        name: promotion_quoter

    datasource:
      url: jdbc:h2:mem:promo_quote
      driver-class-name: org.h2.Driver
      username: kifiya
      password: promo123
      jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
          ddl-auto: update
        h2:
            console:
                enabled: true
                path: /h2-console